---
- hosts: localhost
  connection: local
  tasks:
    - name: Create Resource group
      azure_rm_resourcegroup:
        name: DemoRG
        location: westus
        state: present
        tags:
          testing: demo
          delete: never
      register: rgname
      
    - debug:
        msg: "Resource group created : {{ rgname }}" 
