---
- hosts: localhost
  connection: local
  tasks:
    - name: Create Resource group
      azure_rm_resourcegroup:
        name: DemoRG
        location: westus
        state: present
        tags:
          testing: demo

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: DemoRG
        name: testvn001
        address_prefixes: "192.168.0.0/24"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: DemoRG
        name: subnet001
        address_prefix: "192.168.0.0/25"
        virtual_network: testvn001
